name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to 'main' branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Test on multiple Node.js versions

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code
    - name: Set up Node.js ${{ matrix.node-version }}  # Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci  # Install dependencies
    - run: npm run build  # Build the project (ensure this generates static files in a 'build' or 'dist' folder)

  deploy:
    needs: build  # This job will only run if the build job is successful
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code again

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Action to deploy to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the deployment
        publish_dir: ./build  # Path to the built static files (change this if your build directory is different)
